### ISSUE TITLE
I'd like to ask you to create latest version.

### ISSUE THREAD

**Issue by h-r-k-matsumoto** [getsentry/action-github-app-token#14]
I want to use the latest version including #6 .

#6 has been merged main branch, however build module such [index.js](https://github.com/getsentry/action-github-app-token/blob/main/dist/index.js) is not included #6.

Would you create and publish the latest version?

**Comment by h-r-k-matsumoto** [comment]
Currently, I've been using like this below.

```
h-r-k-matsumoto/action-github-app-token@v1.0.5
```
compare: https://github.com/getsentry/action-github-app-token/compare/main...h-r-k-matsumoto:feature/new-release

However, I'd like to change it to `getsentry/action-github-app-token@v1` which is what it should be.

**Comment by billyvg** [comment]
@h-r-k-matsumoto Sorry about that, we have since merged in #11 which includes an update to the dist bundle. I'd recommend using the commit SHA (`802336f88743ac7da1bd729d6d9ac273c8677240`) as it's a bit more secure since tags are mutable.

**Comment by h-r-k-matsumoto** [comment]
@billyvg  Thank you so much!!
The latest version is available on Enterprise Server without any problems!
It is so grateful!
