### ISSUE TITLE
GitHub marketplace link doesn't work, requesting new release tag

### ISSUE THREAD

**Issue by statik** [getsentry/action-github-app-token#2]
Hi! This action is exactly what I need, thank you for creating and publishing it!

I see the link for the GitHub marketplace is returning not found, and there has been a dependency update since the v1 tag was published.

One question, and one request 😺 
1. Please would you publish a new release tag?
2. Is it intentional that this is not published in GitHub Actions Marketplace? Not sure whether that was deliberate or accidental, and figured I should ask before using this.

Thank you 👍

**Comment by billyvg** [comment]
@statik Sorry this got lost during the holidays - I will publish a new release and fix it in the marketplace.

**Comment by billyvg** [comment]
@statik This should be fixed now, thanks for letting me know!
