### ISSUE TITLE
Action Gives Deprecation Warning

### ISSUE THREAD

**Issue by syoon2** [getsentry/action-github-app-token#50]
### Context

[GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

### Environment

GitHub-hosted runner, `ubuntu-20.04` [Version 20221002.2](https://github.com/actions/runner-images/blob/ubuntu20/20221002.2/images/linux/Ubuntu2004-Readme.md)

### Steps to Reproduce

1. Use this action in workflow

### Expected Result

Action runs without warning.

### Actual Result

Action gives deprecation warning.

**Comment by junze-smg** [comment]
On the same note, node12 is deprecated by Github Actions too. See here https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

I could make a PR if anyone would review and merge it.

**Comment by AJ0351726** [comment]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Could you fix this deprecated ?

**Comment by genehynson** [comment]
I'm actually confused why we're getting this deprecation message. The github [docs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) say:
> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

And `getsentry/action-github-app-token` is using `@actions/core` v1.10.0 already: https://github.com/getsentry/action-github-app-token/blob/main/package.json#L48

**Comment by syoon2** [comment]
Fixed in #53
