### ISSUE TITLE
node 12 deprecated

### ISSUE THREAD

**Issue by AJ0351726** [getsentry/action-github-app-token#52]
### Environment

What version are you running? Etc.

### Steps to Reproduce

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: getsentry/action-github-app-token

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by billyvg** [comment]
Closed by #53
